### ISSUE TITLE
Ensure integration with Biolink KGX

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/dgipy#35]
https://kgx.readthedocs.io/en/latest/

It's possible that everything we'd need to support this is already in place (ie networkx graph output) but maybe it'd be nice to document it.

**Comment by jsstevenson** [comment]
after looking through the biolink schema more, I'm unsure of whether it's worth it (it's very constrictive) but i'll leave this open for now

**Comment by rbasu101** [comment]
@mcannon068nw @jsstevenson and I all seem to be in agreement that integrating biolink kgx is not a worthwhile endeavor (at least in the current stage of dgipy's development). The biolink schema is far too restrictive to be properly integrated with the rest of dgipy, and as showcased in branch '35-ensure-integration-with-biolink-kgx', it requires major restructuring of the existing schema dgipy uses. In the future, dgipy will likely use its own custom schema and exporting functionality that is better fitted for dgipy. Perhaps this will be relooked at in the future, at a later stage in development, but for now I will close this issue.
