### ISSUE TITLE
Use pagination

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/dgipy#57]
Right now, large queries (eg `get_gene_list`) are capped in the # of responses because of (reasonable) server configs. We need to make sure we're employing pagination to get all search results until they're exhausted.

**Comment by mcannon068nw** [comment]
Related, `get_clinical_trials` has a similar pagination issue through the clinicaltrials.gov API that we need to resolve going forward

**Comment by jsstevenson** [comment]
I thought `get_gene_list` was paginated because it's a round number, but actually the true number is round.

**Comment by jsstevenson** [comment]
Note also that we might be moving fda annotation out entirely in favor of the [regbot](https://github.com/GenomicMedLab/regbot) package, which would obviate this

**Comment by jsstevenson** [comment]
Okay I think this is resolved globally
