### ISSUE TITLE
Fix pyproject.toml not installing optional dependencies

### ISSUE THREAD

**Issue by rbasu101** [GenomicMedLab/dgipy#6]
Under the given header:
[project.optional-dependencies]
test = ["pytest", "pytest-cov","pytest-benchmark"]
dev = ["pre-commit", "ruff==0.2.0"]

Running:
python3 -m pip install -e '.[dev,tests]'

Fails to automatically install the pytest-benchmark package 

It is possible that the other pytest packages also are not automatically installed, but this has not been tested yet.

**Comment by jsstevenson** [comment]
Concerning! What's the result of running 'pip show pytest-benchmark'?

**Comment by korikuzma** [comment]
@rbasu101 is it because you are using tests (plural) instead of test (singular) as specified in pyproject.toml?

**Comment by rbasu101** [comment]
> @rbasu101 is it because you are using tests (plural) instead of test (singular) as specified in pyproject.toml?

Funnily enough, this does infact seem to be the problem.

To test this:
I uninstalled all three pytest packages (python3 -m pip uninstall)
I ran python3 -m pip install -e '.[dev,tests]'
Checking python3 -m pip list showed that none of the pytest packages were uninstalled
I ran python3 -m pip install -e '.[dev,test]'
Checking python3 -m pip list showed that all three of the pytest packages properly installed

**Comment by rbasu101** [comment]
Solution will be as easy as either modifying the README to use 'test' instead of 'tests' or using 'tests' in pyproject.toml
