### ISSUE TITLE
500 Server Error after v.5.0.8 release on DGIdb

### ISSUE THREAD

**Issue by mcannon068nw** [GenomicMedLab/dgipy#88]
### Describe the bug

500 Server Error occuring using dgipy get methods to dgidb database. Not sure why this is happening but only started after the v.5.0.8 release earlier today.

```
File "/Users/mjc014/.pyenv/versions/3.11.9/lib/python3.11/site-packages/gql/transport/requests.py", line 250, in raise_response_error
  raise TransportServerError(str(e), e.response.status_code) from e
gql.transport.exceptions.TransportServerError: 500 Server Error: Internal Server Error for url: https://dgidb.org/api/graphql
```

### Steps to reproduce

```
>>> import dgipy
>>> dgipy.get_interactions(['BRAF'])
```

### Expected behavior

It should fetch a large pd.DataFrame()-ready response object.

### Current behavior

```
File "/Users/mjc014/.pyenv/versions/3.11.9/lib/python3.11/site-packages/gql/transport/requests.py", line 250, in raise_response_error
    raise TransportServerError(str(e), e.response.status_code) from e
gql.transport.exceptions.TransportServerError: 500 Server Error: Internal Server Error for url: https://dgidb.org/api/graphql

```

Duplicated from both myself and Rohit's end

### Acceptance Criteria

get_interactions() and related methods should get proper responses and not 500 errors

### Possible reason(s)

Something related to the v.5.0.8 release earlier today? Not sure, all the API endpoints on the server side at DGIdb.org seem to be working just fine, but dgipy calls specifically are giving this error.

### Branch, commit, and/or version

commit: b9ece0667 branch: main

### Environment details

sequoia 15.1.1

### Contribution

None

**Comment by jsstevenson** [comment]
The graphql API is in trouble :( https://dgidb.org/api
